### ISSUE TITLE
Using environment variables

### ISSUE THREAD

**Issue by robertnicjoo** [ncaneldiee/rajaongkir#3]
hi, does this package support env codes?

where should I define my accound `api key` and `type` ?

**Comment by ncaneldiee** [comment]
Yes, just put `env('RAJAONGKIR_API_KEY')` when you initialize class `Rajaongkir\Domestic` (i assumed you has set env `RAJAONGKIR_API_KEY=your-key`) and you can define your account type with constant `Rajaongkir\Domestic::ACCOUNT_STARTER`, `Rajaongkir\Domestic::ACCOUNT_BASIC`, or `Rajaongkir\Domestic::ACCOUNT_PRO` (default is starter)

I hope [this](https://github.com/ncaneldiee/rajaongkir/wiki/Usage#initialization) can help you @robertnicjoo

**Comment by robertnicjoo** [comment]
thanks for respond @ncaneldiee 

`RAJAONGKIR_API_KEY=your-key` goes to my env file
and for my account type should i do like so: (please correct me if i'm wrong)


```php
public function __construct() {
        $rajaongkir = new Rajaongkir\Domestic(YOUR_API_KEY, Rajaongkir\Domestic::ACCOUNT_PRO);
    }
```

sort of strange! isn't it?

**Comment by ncaneldiee** [comment]
I got your point @robertnicjoo, you want to simply using `RAJAONGKIR_API_KEY` and `RAJAONGKIR_API_KEY` in your .env file, right ? Please see this [laravel package config](https://github.com/ncaneldiee/rajaongkir-laravel/blob/master/config/rajaongkir.php) for example, i use this package for laravel project one year ago, and laravel using .env file

**Comment by robertnicjoo** [comment]
@ncaneldiee  yes that's what i'm looking for, but there is no artisan command in documentation to publish config file and there is no config file in vendor either! should i make this config file manually?


![untitled](https://user-images.githubusercontent.com/8672823/35260515-a219231c-003e-11e8-9814-6388c325476c.png)

**Comment by ncaneldiee** [comment]
Try `artisan vendor:publish`, see [this](https://github.com/ncaneldiee/rajaongkir-laravel/blob/1e3611238e50c0930c1de18f1bc9df9236626447/src/RajaongkirServiceProvider.php#L15). FYI, for laravel you need load other package https://github.com/ncaneldiee/rajaongkir-laravel

**Comment by robertnicjoo** [comment]
@ncaneldiee  ok there was a mistake by me sorry about that, i used this package instead of laravel version which is [this ](https://github.com/ncaneldiee/rajaongkir-laravel) currently i try to install that package, while is processing one question?

don't you think it suppose to have `::class` after `provider` and `aliases` ?

your code:

```php
'Ncaneldiee\Rajaongkir\Laravel\RajaongkirServiceProvider',

'Rajaongkir\Domestic' => 'Ncaneldiee\Rajaongkir\Laravel\RajaongkirDomesticFacade',
'Rajaongkir\International' => 'Ncaneldiee\Rajaongkir\Laravel\RajaongkirInternationalFacade',
```

my idea: 

```php
Ncaneldiee\Rajaongkir\Laravel\RajaongkirServiceProvider::class,

'Rajaongkir\Domestic' => Ncaneldiee\Rajaongkir\Laravel\RajaongkirDomesticFacade::class,
'Rajaongkir\International' => Ncaneldiee\Rajaongkir\Laravel\RajaongkirInternationalFacade::class,
```

what do you think?

**Comment by ncaneldiee** [comment]
I think both will work, but your PR is very welcome expecially with auto discovery package feature
